<a href="https://colab.research.google.com/github/semreyalcin/CNG562-HW2/blob/master/YALCIN_otto_group_product_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selim Emre Yalçın
2152205

Otto Group Product Classifiacation

#Preparing Data

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
train_url = 'https://raw.githubusercontent.com/semreyalcin/CNG562-HW2/master/Otto%20Group%20Product%20Classification/train.csv'
data = pd.read_csv(train_url)
data.head()

   id  feat_1  feat_2  feat_3  ...  feat_91  feat_92  feat_93   target
0   1       1       0       0  ...        0        0        0  Class_1
1   2       0       0       0  ...        0        0        0  Class_1
2   3       0       0       0  ...        0        0        0  Class_1
3   4       1       0       0  ...        0        0        0  Class_1
4   5       0       0       0  ...        0        0        0  Class_1

[5 rows x 95 columns]

In [2]:
y = data['target']
X = data.drop(['target','id'],axis = 1)
data.head(),X.head(),y.head()

(   id  feat_1  feat_2  feat_3  ...  feat_91  feat_92  feat_93   target
 0   1       1       0       0  ...        0        0        0  Class_1
 1   2       0       0       0  ...        0        0        0  Class_1
 2   3       0       0       0  ...        0        0        0  Class_1
 3   4       1       0       0  ...        0        0        0  Class_1
 4   5       0       0       0  ...        0        0        0  Class_1

 [5 rows x 95 columns],
    feat_1  feat_2  feat_3  feat_4  ...  feat_90  feat_91  feat_92  feat_93
 0       1       0       0       0  ...        0        0        0        0
 1       0       0       0       0  ...        0        0        0        0
 2       0       0       0       0  ...        0        0        0        0
 3       1       0       0       1  ...        0        0        0        0
 4       0       0       0       0  ...        1        0        0        0

 [5 rows x 93 columns],
 0    Class_1
 1    Class_1
 2    Class_1
 3    Class_1
 4    Class_1
 Name: target, dtype: object)

#Multi-Layered Perceptron

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [4]:
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(solver='adam', 
                    alpha=1e-5,
                    hidden_layer_sizes=(25, 15), 
                    random_state=21,
                    shuffle = True,
                    max_iter = 300,
                    early_stopping = True,
                    verbose = True)

MLP.fit(X_train, y_train)

Iteration 1, loss = 1.19644945
Validation score: 0.713391
Iteration 2, loss = 0.73463543
Validation score: 0.750757
Iteration 3, loss = 0.66313899
Validation score: 0.760452
Iteration 4, loss = 0.63306972
Validation score: 0.769138
Iteration 5, loss = 0.61413089
Validation score: 0.770753
Iteration 6, loss = 0.59987196
Validation score: 0.772975
Iteration 7, loss = 0.58808195
Validation score: 0.777621
Iteration 8, loss = 0.57943555
Validation score: 0.775399
Iteration 9, loss = 0.56960361
Validation score: 0.781458
Iteration 10, loss = 0.56200037
Validation score: 0.783276
Iteration 11, loss = 0.55554429
Validation score: 0.782064
Iteration 12, loss = 0.55014506
Validation score: 0.786104
Iteration 13, loss = 0.54452945
Validation score: 0.785498
Iteration 14, loss = 0.53997156
Validation score: 0.786710
Iteration 15, loss = 0.53698962
Validation score: 0.789134
Iteration 16, loss = 0.53293473
Validation score: 0.790345
Iteration 17, loss = 0.52990017
Validation score: 0.790547
Iteration 18, loss = 0.52665994
Validation score: 0.789537
Iteration 19, loss = 0.52451121
Validation score: 0.791355
Iteration 20, loss = 0.52186339
Validation score: 0.788326
Iteration 21, loss = 0.51939226
Validation score: 0.788124
Iteration 22, loss = 0.51735238
Validation score: 0.790749
Iteration 23, loss = 0.51635542
Validation score: 0.788730
Iteration 24, loss = 0.51385952
Validation score: 0.790951
Iteration 25, loss = 0.51173790
Validation score: 0.790951
Iteration 26, loss = 0.50952862
Validation score: 0.787114
Iteration 27, loss = 0.50885802
Validation score: 0.790345
Iteration 28, loss = 0.50628213
Validation score: 0.792163
Iteration 29, loss = 0.50517029
Validation score: 0.790345
Iteration 30, loss = 0.50302377
Validation score: 0.787922
Iteration 31, loss = 0.50297821
Validation score: 0.789335
Iteration 32, loss = 0.50117969
Validation score: 0.788932
Iteration 33, loss = 0.49949680
Validation score: 0.791557
Iteration 34, loss = 0.49820441
Validation score: 0.790951
Iteration 35, loss = 0.49746151
Validation score: 0.788932
Iteration 36, loss = 0.49761499
Validation score: 0.790951
Iteration 37, loss = 0.49530474
Validation score: 0.793577
Iteration 38, loss = 0.49482866
Validation score: 0.789739
Iteration 39, loss = 0.49364470
Validation score: 0.791153
Iteration 40, loss = 0.49261076
Validation score: 0.793981
Iteration 41, loss = 0.49237901
Validation score: 0.788124
Iteration 42, loss = 0.49116742
Validation score: 0.790547
Iteration 43, loss = 0.49043097
Validation score: 0.794183
Iteration 44, loss = 0.48989780
Validation score: 0.794587
Iteration 45, loss = 0.48866529
Validation score: 0.790951
Iteration 46, loss = 0.48780499
Validation score: 0.789739
Iteration 47, loss = 0.48806775
Validation score: 0.791355
Iteration 48, loss = 0.48713217
Validation score: 0.791961
Iteration 49, loss = 0.48626895
Validation score: 0.788730
Iteration 50, loss = 0.48553441
Validation score: 0.789941
Iteration 51, loss = 0.48454351
Validation score: 0.792163
Iteration 52, loss = 0.48439485
Validation score: 0.790345
Iteration 53, loss = 0.48332611
Validation score: 0.788326
Iteration 54, loss = 0.48247698
Validation score: 0.785902
Iteration 55, loss = 0.48332974
Validation score: 0.793375
Validation score did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=True, epsilon=1e-08,
              hidden_layer_sizes=(25, 15), learning_rate='constant',
              learning_rate_init=0.001, max_iter=300, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=21, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=True, warm_start=False)

In [5]:
from sklearn.metrics import accuracy_score
acc_MLP = accuracy_score(y_test, MLP.predict(X_test))
acc_MLP

0.7771493212669683

#KNN

In [0]:
from sklearn.neighbors import KNeighborsClassifier

KNN = KNeighborsClassifier(n_neighbors=5).fit(X_train,y_train)
acc_KNN = accuracy_score(y_test, KNN.predict(X_test))
acc_KNN

# Support Vector Machine

In [0]:
from sklearn.svm import SVC 
SVM = SVC().fit(X_train,y_train)
acc_SVM = accuracy_score(y_test, SVM.predict(X_test))
acc_SVM

#XGBoost

In [0]:
from xgboost import XGBClassifier

XGB = XGBClassifier().fit(X_train,y_train)
acc_XGB = accuracy_score(y_test, XGB.predict(X_test))
acc_XGB

#Result Comparison

In [0]:
"Classifier  |  Result",
"MLP:        |  " + str(acc_MLP),
"KNN:        |  " + str(acc_KNN),
"SVM:        |  " + str(acc_SVM),
"XGB:        |  " + str(acc_XGB)